/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 存活探针 */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/corpus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 上传文献文件并异步解析为语料 (状态机入口, Codex-5)
         * @description 幂等: Phase 1 (T10) 起强制 — 携带 Idempotency-Key 时, 相同 (key, projectId) 的重试 返回同一 corpus; 未带 key 时以 (contentHash, dbsource, projectId) 去重。 Phase 0: 接受 Idempotency-Key 头但暂不去重 (Codex step3-P2, 不过度声称)。
         */
        post: operations["createCorpus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/corpus/from-topic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 主题词检索建库 (路径 A, OpenAlex)
         * @description 输入研究主题词, 经 OpenAlex 检索近 N 年文献并补全引用题录, 组装为 WoS plaintext 后由 bibliometrix 建为可分析语料。同步返回 (Phase 0)。
         */
        post: operations["createCorpusFromTopic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/corpus/from-refs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 参考文献文本建库 (路径 B, LLM 抽取 + OpenAlex 反查)
         * @description 粘贴非结构化参考文献文本, agent 用 LLM 抽取题录, 再经 OpenAlex 反查补全 元数据并建为语料。响应含 matched/unmatched/extracted 统计。
         */
        post: operations["createCorpusFromRefs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/corpus/materialize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * M2: 物化项目 included 论文为可分析语料（幂等）
         * @description 从项目当前 included 论文集合构建冻结语料快照，并调 R /parse-from-records 建库。 幂等：相同 included 集合（content_hash 一致）命中已有 ready corpus 直接复用。 included 为空时返回 422 EMPTY_INCLUDED。
         */
        post: operations["materializeCorpus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/corpus/{corpusId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询语料状态, 前端据此 gating (Codex-5) */
        get: operations["getCorpus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/corpus/{corpusId}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 领域概览分析, 仅 status=ready 可取 */
        get: operations["getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/corpus/{corpusId}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 来源分析 (核心期刊/h指数/Bradford) */
        get: operations["getSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/corpus/{corpusId}/authors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 作者分析 (高产作者/h指数/Lotka) */
        get: operations["getAuthors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/corpus/{corpusId}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 文档与关键词 (高被引/词频) */
        get: operations["getDocuments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/corpus/{corpusId}/authors/production": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 作者年度产出时间线 (热力图: 作者 × 年份, A4)
         * @description 返回可用性信封; available:false 也是 HTTP 200。需 PY 字段。
         */
        get: operations["getAuthorProduction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/corpus/{corpusId}/documents/keyword-trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 关键词历时演变 (themeRiver / 堆叠面积, A4)
         * @description 返回可用性信封; available:false 也是 HTTP 200。需 DE+PY 字段。
         */
        get: operations["getKeywordTrend"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/corpus/{corpusId}/documents/cited-refs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 高被引参考文献表 (参考文献 | 次数, A4)
         * @description 返回可用性信封; available:false 也是 HTTP 200。需 CR 字段。
         */
        get: operations["getCitedRefs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/corpus/{corpusId}/conceptual/thematic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 主题战略图 (Callon 中心度×密度 四象限, A5)
         * @description 返回可用性信封; available:false 也是 HTTP 200。需 DE 字段。
         */
        get: operations["getThematic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/corpus/{corpusId}/conceptual/evolution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 主题演进图 (多周期主题流 / Sankey, A5)
         * @description 返回可用性信封; available:false 也是 HTTP 200。需 DE+PY 且跨度可切≥2 周期。
         */
        get: operations["getEvolution"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/corpus/{corpusId}/intellectual/histcite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 历史引文图 (时序分层引用脉络, A5)
         * @description 返回可用性信封; available:false 也是 HTTP 200。需 CR 字段; 节点<2 → not_enough_data。
         */
        get: operations["getHistcite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/corpus/{corpusId}/overview/threefield": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 三字段 Sankey (作者→关键词→来源, A5)
         * @description 返回可用性信封; available:false 也是 HTTP 200。需 AU+DE+SO 字段。
         */
        get: operations["getThreeField"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/corpus/{corpusId}/conceptual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 概念结构 (关键词共现网络) */
        get: operations["getConceptual"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/corpus/{corpusId}/intellectual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 知识结构 (参考文献共被引网络) */
        get: operations["getIntellectual"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/corpus/{corpusId}/social": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 社会结构 (作者/国家合作网络) */
        get: operations["getSocial"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 全局文献库统计（totalPapers/withMetadata/withPdf/OCR分布） */
        get: operations["getLibraryStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/library/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 项目作用域文献库统计（含纳排分布） */
        get: operations["getProjectLibraryStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/papers/{paperId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取项目内单篇文献详情（含 tags/notes/纳排状态/结构化抽取结果） */
        get: operations["getPaperDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/papers/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 导入 PDF/ZIP 到项目文献库（幂等，M1 BLOCKER）
         * @description multipart/form-data 上传一个或多个 .pdf 文件，或一个包含 PDF 的 .zip 文件。
         *     流程：解压(若 ZIP) → 逐篇 ingest_pdfs（已有 sha256 缓存直接复用，不重复 MinerU） → add_paper（dedup by DOI or title hash）→ add_paper_to_project（默认 candidate）。
         *     幂等：同一 PDF 重复导入（sha256/dedup_key 命中）→ skipped 计数增加，不报错， paperIds 仍含该 id。
         *     refs 文本（纯 DOI/题录）本期暂不支持，请使用 POST /projects/{projectId}/corpus/from-refs。
         */
        post: operations["importPapers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/papers/from-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 把检索候选批量入库并关联到项目（幂等，P2-T3）
         * @description 接收来自 SearchTool 检索到的候选列表，逐条 add_paper（DOI/title dedup）→ add_paper_to_project（默认 candidate）。
         *     defaultStatus=included 时，关联后再调 set_inclusion 将状态升级为 included。
         *     幂等：同一候选（DOI/title 命中）重复提交 → skipped+1，不报错，paperIds 仍含该 id。
         */
        post: operations["addPapersFromSearch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/papers/backfill-metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * AI 元数据补全：用 LLM 从已 OCR 全文回填缺失题录（P3-T1）
         * @description 对项目内 OCR-done 且缺 abstract 或 creators 的文献，用 LLM 读取 Markdown 全文首部 抽取元数据，仅回填当前为空的字段，不覆盖已有内容。
         *     逐篇失败隔离：单篇 LLM/JSON/DB 错误不影响批次其他篇。 支持 X-LLM-Key 头（用户自带 key）；无 key 时回退服务端 DEEPSEEK。
         */
        post: operations["backfillMetadata"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/papers/extract-structured": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * AI 结构化抽取：用 LLM 从已 OCR 全文抽取研究要素（P3-T3）
         * @description 对项目内 OCR-done 的文献，用 LLM 读取 Markdown 全文首部， 抽取 research_question/method/findings/dataset/contribution 五字段， 幂等 upsert 到 paper_extraction 表。
         *     reextract=false（默认）：已有 extraction 的篇自动跳过；reextract=true：强制覆盖更新。 逐篇失败隔离：单篇 LLM/JSON/DB 错误不影响批次其他篇。 支持 X-LLM-Key 头（用户自带 key）；无 key 时回退服务端 DEEPSEEK。
         */
        post: operations["extractStructured"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/prisma": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** PRISMA 2020 流程图计数 + 一致性校验 */
        post: operations["buildPrisma"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/corpus/{corpusId}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 导出分析报告 (Markdown / HTML / DOCX 附件下载)
         * @description A7: POST + ReportOptions(title/author/sections/可选 prismaCounts/reviewMarkdown); format 走 query (md/html/docx)。DOCX 经 pandoc 转换, 服务端缺 pandoc 时返回 503, 前端据此降级仅显示 md/html。
         */
        post: operations["exportReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/ai/translate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 文献翻译 (en2zh / zh2en) */
        post: operations["aiTranslate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/ai/rewrite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 交互重写 (counter/compress/expand/casual) */
        post: operations["aiRewrite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/ai/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 文本总结 */
        post: operations["aiSummary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/corpus/{corpusId}/ai/screen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 相关性筛选 (批量给语料文献打分) */
        post: operations["aiScreen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/corpus/{corpusId}/ai/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 与语料对话 (SSE 流式)
         * @description SSE 流, 事件 token/done/error。X-LLM-Key 透传不落盘。
         */
        post: operations["aiChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/corpus/{corpusId}/cite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 引用导出 (GB/T 7714 / APA / MLA) */
        get: operations["getCite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/corpus/{corpusId}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 流式生成综述 (SSE)
         * @description SSE 流 (text/event-stream)。事件: meta(模板+章节) / chapter(章节开始) / token(增量正文) / citations(引用校验 summary+annotated) / done / error。 用户自带 LLM key 经 X-LLM-Key 头透传, 不落盘 (沿用 v0.6)。前端用 fetch+ReadableStream 消费 (非 EventSource, 因需 POST body + 自定义头)。
         */
        post: operations["streamReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出项目工件（可按 pinned 过滤） */
        get: operations["listArtifacts"];
        put?: never;
        /** 创建/pin 工件 */
        post: operations["createArtifact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{pid}/artifacts/{aid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除工件 */
        delete: operations["deleteArtifact"];
        options?: never;
        head?: never;
        /** 更新工件（title/annotation/pinned/order） */
        patch: operations["patchArtifact"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok";
            /** @example agent */
            service: string;
            /**
             * @description 下游 R 分析服务可达性
             * @enum {string}
             */
            rService?: "up" | "down" | "unknown";
        };
        /**
         * @description 数据来源, 切片1 仅 wos/scopus, pubmed/openalex 后续 (Codex-13)
         * @enum {string}
         */
        DbSource: "wos" | "scopus";
        /**
         * @description 语料状态机 (Codex-5)
         * @enum {string}
         */
        CorpusStatus: "parsing" | "ready" | "failed";
        CorpusBase: {
            /** Format: uuid */
            corpusId: string;
            projectId: string;
            status: components["schemas"]["CorpusStatus"];
            /**
             * @description artifact schema 版本 (Codex-2/Codex-10)
             * @constant
             */
            schemaVersion: 1;
            dbsource: components["schemas"]["DbSource"];
            /** Format: date-time */
            createdAt: string;
        };
        CorpusParsing: components["schemas"]["CorpusBase"] & {
            /** @constant */
            status: "parsing";
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "parsing";
        };
        CorpusReady: components["schemas"]["CorpusBase"] & {
            /** @constant */
            status: "ready";
            documentCount: number;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "ready";
        };
        CorpusFailed: components["schemas"]["CorpusBase"] & {
            /** @constant */
            status: "failed";
            /** @description 失败原因, 已脱敏 (Codex-18) */
            error: string;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "failed";
        };
        CorpusRef: components["schemas"]["CorpusParsing"] | components["schemas"]["CorpusReady"] | components["schemas"]["CorpusFailed"];
        /** @description 项目当前 active corpus 摘要，内嵌于 ProjectDetail。 corpusId 为 Postgres DB integer；rCorpusId 为 R 字符串 ID（调分析端点时透传）。 stale=true 表示当前 included 集合与本 corpus 的 contentHash 不同，需重算。 */
        ActiveCorpusDetail: {
            /** @description Postgres DB corpus.id */
            corpusId: number;
            /** @description R 字符串语料 ID；status != ready 时为 null */
            rCorpusId?: string | null;
            /** @enum {string} */
            status: "parsing" | "ready" | "failed";
            documentCount: number;
            /** @description included 集合指纹（sha256） */
            contentHash: string;
            /** @description 当前 included 集合与 corpus 快照不同时为 true */
            stale: boolean;
        };
        /** @description POST /projects/{pid}/corpus/materialize 响应体 */
        CorpusMaterializeResponse: {
            /** @description Postgres DB corpus.id */
            corpusId: number;
            /** @description R 字符串语料 ID；status=parsing/failed 时为 null */
            rCorpusId?: string | null;
            /** @enum {string} */
            status: "parsing" | "ready" | "failed";
            documentCount: number;
            contentHash: string;
        };
        TopicRequest: {
            /** @description 研究主题词 (中英皆可, OpenAlex 全文检索) */
            query: string;
            /**
             * @description 取多少篇主论文
             * @default 50
             */
            n: number;
            /**
             * @description 发表日下限 (YYYY-MM-DD)
             * @default 2016-01-01
             */
            since: string;
            /**
             * @description 是否同步补全引用题录 (慢但完整)
             * @default true
             */
            withRefs: boolean;
        };
        RefsRequest: {
            /** @description 非结构化参考文献文本 (清单/Google Scholar/APA 等) */
            text: string;
            /** @default true */
            withRefs: boolean;
        };
        OverviewResult: {
            /** @constant */
            schemaVersion: 1;
            /** @description 跨项目防错锚点 (step1-P2) */
            projectId: string;
            /** Format: uuid */
            corpusId: string;
            stats: components["schemas"]["OverviewStats"];
            annualProduction: components["schemas"]["AnnualPoint"][];
        };
        OverviewStats: {
            documents: number;
            /** @description 期刊或来源数 */
            sources: number;
            authors: number;
            keywordsPlus?: number | null;
            authorKeywords?: number | null;
            avgCitationsPerDoc: number;
            /** @description 起始年 */
            timespanFrom: number;
            /** @description 结束年 */
            timespanTo: number;
            hIndex?: number | null;
            /** @description 年均增长率 CAGR (%); 单年/边界为 null */
            annualGrowthRate?: number | null;
        };
        AnnualPoint: {
            year: number;
            articles: number;
        };
        SourceItem: {
            source: string;
            articles: number;
        };
        HSourceItem: {
            source: string;
            h: number;
            g?: number | null;
            m?: number | null;
            tc?: number | null;
        };
        BradfordItem: {
            source: string;
            zone: string;
            freq: number;
            rank?: number | null;
            cumPct?: number | null;
        };
        SourcesResult: {
            /** @constant */
            schemaVersion: 1;
            projectId: string;
            /** Format: uuid */
            corpusId: string;
            topSources: components["schemas"]["SourceItem"][];
            hIndex: components["schemas"]["HSourceItem"][];
            bradford: components["schemas"]["BradfordItem"][];
        };
        AuthorItem: {
            author: string;
            articles: number;
        };
        HAuthorItem: {
            author: string;
            h: number;
            g?: number | null;
            m?: number | null;
            tc?: number | null;
        };
        LotkaPoint: {
            articles: number;
            authors: number;
        };
        Lotka: {
            beta?: number | null;
            distribution?: components["schemas"]["LotkaPoint"][];
        };
        AuthorsResult: {
            /** @constant */
            schemaVersion: 1;
            projectId: string;
            /** Format: uuid */
            corpusId: string;
            topAuthors: components["schemas"]["AuthorItem"][];
            hIndex: components["schemas"]["HAuthorItem"][];
            lotka: components["schemas"]["Lotka"];
        };
        CitedDoc: {
            title?: string | null;
            author?: string | null;
            year?: number | null;
            cited: number;
        };
        KeywordItem: {
            term: string;
            freq: number;
        };
        DocumentsResult: {
            /** @constant */
            schemaVersion: 1;
            projectId: string;
            /** Format: uuid */
            corpusId: string;
            topCited: components["schemas"]["CitedDoc"][];
            keywords: components["schemas"]["KeywordItem"][];
        };
        /**
         * @description 高级图不可用原因 (区分 missing_field/not_enough_data/computed_empty/analysis_error)
         * @enum {string}
         */
        AnalysisUnavailableReason: "missing_field" | "not_enough_data" | "computed_empty" | "analysis_error";
        AnalysisUnavailable: {
            /** @enum {boolean} */
            available: false;
            reason: components["schemas"]["AnalysisUnavailableReason"];
            missingField?: string | null;
            message: string;
            howto?: string | null;
            detail?: string | null;
            schemaVersion?: number | null;
            corpusId?: string | null;
            projectId?: string | null;
        };
        AuthorProductionCell: {
            author: string;
            year: number;
            articles: number;
        };
        AuthorProductionData: {
            authors: string[];
            years: number[];
            cells: components["schemas"]["AuthorProductionCell"][];
        };
        AuthorProductionOk: {
            /** @enum {boolean} */
            available: true;
            data: components["schemas"]["AuthorProductionData"];
            schemaVersion?: number | null;
            corpusId?: string | null;
            projectId?: string | null;
        };
        AuthorProductionEnvelope: components["schemas"]["AuthorProductionOk"] | components["schemas"]["AnalysisUnavailable"];
        KeywordTrendCell: {
            year: number;
            term: string;
            freq: number;
        };
        KeywordTrendData: {
            years: number[];
            terms: string[];
            cells: components["schemas"]["KeywordTrendCell"][];
        };
        KeywordTrendOk: {
            /** @enum {boolean} */
            available: true;
            data: components["schemas"]["KeywordTrendData"];
            schemaVersion?: number | null;
            corpusId?: string | null;
            projectId?: string | null;
        };
        KeywordTrendEnvelope: components["schemas"]["KeywordTrendOk"] | components["schemas"]["AnalysisUnavailable"];
        CitedRefItem: {
            ref: string;
            count: number;
        };
        CitedRefsOk: {
            /** @enum {boolean} */
            available: true;
            data: components["schemas"]["CitedRefItem"][];
            schemaVersion?: number | null;
            corpusId?: string | null;
            projectId?: string | null;
        };
        CitedRefsEnvelope: components["schemas"]["CitedRefsOk"] | components["schemas"]["AnalysisUnavailable"];
        ThematicCluster: {
            label: string;
            centrality: number;
            density: number;
            freq: number;
        };
        ThematicData: {
            clusters: components["schemas"]["ThematicCluster"][];
        };
        ThematicOk: {
            /** @enum {boolean} */
            available: true;
            data: components["schemas"]["ThematicData"];
            schemaVersion?: number | null;
            corpusId?: string | null;
            projectId?: string | null;
        };
        ThematicEnvelope: components["schemas"]["ThematicOk"] | components["schemas"]["AnalysisUnavailable"];
        EvolutionNode: {
            name: string;
            period: string;
            id: number;
        };
        EvolutionLink: {
            source: number;
            target: number;
            value: number;
        };
        EvolutionData: {
            nodes: components["schemas"]["EvolutionNode"][];
            links: components["schemas"]["EvolutionLink"][];
        };
        EvolutionOk: {
            /** @enum {boolean} */
            available: true;
            data: components["schemas"]["EvolutionData"];
            schemaVersion?: number | null;
            corpusId?: string | null;
            projectId?: string | null;
        };
        EvolutionEnvelope: components["schemas"]["EvolutionOk"] | components["schemas"]["AnalysisUnavailable"];
        HistciteNode: {
            id: string;
            year?: number | null;
            label: string;
            localCites: number;
        };
        HistciteEdge: {
            from: string;
            to: string;
        };
        HistciteData: {
            nodes: components["schemas"]["HistciteNode"][];
            edges: components["schemas"]["HistciteEdge"][];
        };
        HistciteOk: {
            /** @enum {boolean} */
            available: true;
            data: components["schemas"]["HistciteData"];
            schemaVersion?: number | null;
            corpusId?: string | null;
            projectId?: string | null;
        };
        HistciteEnvelope: components["schemas"]["HistciteOk"] | components["schemas"]["AnalysisUnavailable"];
        ThreeFieldNode: {
            name: string;
            layer: number;
        };
        ThreeFieldLink: {
            source: string;
            target: string;
            value: number;
        };
        ThreeFieldData: {
            nodes: components["schemas"]["ThreeFieldNode"][];
            links: components["schemas"]["ThreeFieldLink"][];
        };
        ThreeFieldOk: {
            /** @enum {boolean} */
            available: true;
            data: components["schemas"]["ThreeFieldData"];
            schemaVersion?: number | null;
            corpusId?: string | null;
            projectId?: string | null;
        };
        ThreeFieldEnvelope: components["schemas"]["ThreeFieldOk"] | components["schemas"]["AnalysisUnavailable"];
        GraphNode: {
            id: string;
            label: string;
            value: number;
        };
        GraphEdge: {
            source: string;
            target: string;
            weight: number;
        };
        Graph: {
            nodes: components["schemas"]["GraphNode"][];
            edges: components["schemas"]["GraphEdge"][];
        };
        NetworkResult: {
            /** @constant */
            schemaVersion: 1;
            projectId: string;
            /** Format: uuid */
            corpusId: string;
            /** @description 网络类型标识 */
            network: string;
            graph: components["schemas"]["Graph"];
        };
        SocialResult: {
            /** @constant */
            schemaVersion: 1;
            projectId: string;
            /** Format: uuid */
            corpusId: string;
            authorCollab: components["schemas"]["Graph"];
            countryCollab: components["schemas"]["Graph"];
        };
        PrismaRequest: {
            identified: number;
            duplicates: number;
            screened: number;
            excluded: number;
            included: number;
        };
        PrismaStage: {
            key: string;
            label: string;
            count: number;
        };
        PrismaResult: {
            /** @constant */
            schemaVersion: 1;
            stages: components["schemas"]["PrismaStage"][];
            warnings: string[];
        };
        TranslateRequest: {
            text: string;
            /** @enum {string} */
            direction: "en2zh" | "zh2en";
        };
        RewriteRequest: {
            text: string;
            /** @enum {string} */
            action: "counter" | "compress" | "expand" | "casual";
        };
        SummaryRequest: {
            text: string;
        };
        TextResult: {
            text: string;
        };
        ScreenRequest: {
            topic: string;
            /** @default 10 */
            limit: number;
        };
        ScreenItem: {
            idx: number;
            relevance?: number | null;
            reason: string;
        };
        ScreenResult: {
            results: components["schemas"]["ScreenItem"][];
        };
        ChatMessage: {
            /** @enum {string} */
            role: "user" | "assistant";
            content: string;
        };
        ChatRequest: {
            query: string;
            history?: components["schemas"]["ChatMessage"][];
        };
        CiteResult: {
            /** @constant */
            schemaVersion: 1;
            projectId: string;
            /** Format: uuid */
            corpusId: string;
            /** @enum {string} */
            style: "gbt7714" | "apa" | "mla";
            citations: string[];
        };
        /** @description A7 报告 PRISMA 章节计数 (可选外部内容) */
        PrismaCounts: {
            identified: number;
            duplicates: number;
            screened: number;
            excluded: number;
            included: number;
        };
        /** @description A7 报告导出选项。所有字段可省略(请求体可空); 服务端默认: title="文献计量分析报告", sections=[overview,sources,authors,documents,references]。sections 若提供须非空(minItems:1)。 prismaCounts/reviewMarkdown 为可选外部内容, 前端有则传, 无则对应 section 渲染"未提供"提示。 (不在 schema 写 default 关键字: openapi-typescript 会据此把字段标为必填, 破坏"可省略"契约。) */
        ReportOptions: {
            title?: string;
            author?: string | null;
            sections?: ("overview" | "sources" | "authors" | "documents" | "references" | "prisma" | "review")[];
            prismaCounts?: components["schemas"]["PrismaCounts"];
            reviewMarkdown?: string | null;
        };
        ReviewRequest: {
            /**
             * @description 论型
             * @enum {string}
             */
            type: "undergrad" | "master" | "phd" | "grant" | "proposal" | "sci_intro";
            topic: string;
        };
        ApiErrorBase: {
            /** @enum {string} */
            code: "VALIDATION_ERROR" | "CORPUS_NOT_FOUND" | "CORPUS_NOT_READY" | "PARSE_FAILED" | "ANALYSIS_FAILED" | "R_SERVICE_UNAVAILABLE" | "PAYLOAD_TOO_LARGE" | "UNSUPPORTED_FILE" | "INTERNAL";
            /** @description 人类可读, 已脱敏 (Codex-18) */
            message: string;
            details?: {
                [key: string]: unknown;
            } | null;
        };
        ApiError: components["schemas"]["ApiErrorBase"];
        ErrValidation: components["schemas"]["ApiErrorBase"] & {
            /** @constant */
            code?: "VALIDATION_ERROR";
        };
        ErrNotFound: components["schemas"]["ApiErrorBase"] & {
            /** @constant */
            code?: "CORPUS_NOT_FOUND";
        };
        ErrPayloadTooLarge: components["schemas"]["ApiErrorBase"] & {
            /** @constant */
            code?: "PAYLOAD_TOO_LARGE";
        };
        ErrUnsupportedFile: components["schemas"]["ApiErrorBase"] & {
            /** @constant */
            code?: "UNSUPPORTED_FILE";
        };
        ErrNotReady: components["schemas"]["ApiErrorBase"] & {
            /** @constant */
            code?: "CORPUS_NOT_READY";
        };
        ErrParseFailed: components["schemas"]["ApiErrorBase"] & {
            /** @constant */
            code?: "PARSE_FAILED";
        };
        ErrAnalysisFailed: components["schemas"]["ApiErrorBase"] & {
            /** @constant */
            code?: "ANALYSIS_FAILED";
        };
        ErrRUnavailable: components["schemas"]["ApiErrorBase"] & {
            /** @constant */
            code?: "R_SERVICE_UNAVAILABLE";
        };
        ImportFailedItem: {
            /** @description 文件名（含扩展名） */
            name: string;
            /** @description 失败原因描述 */
            reason: string;
        };
        PapersImportResponse: {
            /** @description 本次新导入（首次关联到项目）的文献数 */
            imported: number;
            /** @description 幂等跳过（paper 已存在于项目）的文献数 */
            skipped: number;
            /** @description 解析/入库失败的文献清单（空数组表示全部成功） */
            failed: components["schemas"]["ImportFailedItem"][];
            /** @description 所有成功入库的 paper DB id（含 imported + skipped 两类） */
            paperIds: number[];
        };
        ArtifactItem: {
            id: number;
            projectId: number;
            runId?: number | null;
            /** @description review | analysis | extraction | paperset */
            type: string;
            title: string;
            sourceEventSeq?: number | null;
            /** @description 内容定位符（如 run:{runId}），供前端取 RunLog 内容 */
            contentRef?: string | null;
            pinned: boolean;
            userAnnotation?: string | null;
            order: number;
            /** Format: date-time */
            createdAt?: string | null;
        };
        ArtifactCreateRequest: {
            /** @default review */
            type: string;
            title?: string;
            runId?: number | null;
            sourceEventSeq?: number | null;
            contentRef?: string | null;
            /** @default false */
            pinned: boolean;
            userAnnotation?: string | null;
            /** @default 0 */
            order: number;
        };
        ArtifactPatchRequest: {
            title?: string | null;
            pinned?: boolean | null;
            userAnnotation?: string | null;
            order?: number | null;
        };
        OcrBreakdown: {
            done: number;
            processing: number;
            pending: number;
            failed: number;
            none: number;
        };
        LibraryStats: {
            totalPapers: number;
            withMetadata: number;
            withPdf: number;
            ocr: components["schemas"]["OcrBreakdown"];
        };
        InclusionBreakdown: {
            included: number;
            candidate: number;
            excluded: number;
            maybe: number;
        };
        ProjectLibraryStats: {
            projectPapers: number;
            inclusion: components["schemas"]["InclusionBreakdown"];
            withMetadata: number;
            withPdf: number;
            ocr: components["schemas"]["OcrBreakdown"];
        };
        ProjectPaperItem: {
            paperId: number;
            title?: string | null;
            year?: number | null;
            source?: string | null;
            /** @enum {string} */
            inclusionStatus: "candidate" | "included" | "excluded" | "maybe";
            screeningScore?: number | null;
            hasAbstract: boolean;
            hasPdf: boolean;
            /** @enum {string} */
            ocrStatus: "none" | "pending" | "processing" | "done" | "failed";
            /** @description 是否已有结构化抽取结果（paper_extraction 表中存在对应行） */
            hasExtraction: boolean;
        };
        FromSearchCandidate: {
            title: string;
            doi?: string | null;
            authors?: string[];
            year?: number | null;
            abstract?: string | null;
            containerTitle?: string | null;
            url?: string | null;
            openalexId?: string | null;
            source?: string | null;
        };
        FromSearchRequest: {
            candidates: components["schemas"]["FromSearchCandidate"][];
            /** @enum {string} */
            defaultStatus?: "candidate" | "included";
        };
        FromSearchResult: {
            /** @description 本次新导入（首次关联到项目）的文献数 */
            imported: number;
            /** @description 幂等跳过（paper 已存在于项目）的文献数 */
            skipped: number;
            /** @description 处理失败的候选数（单条异常，不影响其他候选） */
            failed: number;
            /** @description 所有成功入库的 paper DB id（含 imported + skipped 两类） */
            paperIds: number[];
        };
        BackfillMetadataRequest: {
            /** @description 最多处理的文献数（保配额） */
            limit?: number;
            /** @description True=仅处理缺 abstract 或 creators 的篇；False=全量 */
            onlyMissing?: boolean;
        };
        BackfillMetadataResult: {
            /** @description 本次处理的文献总数 */
            processed: number;
            /** @description 成功回填（至少一个字段更新）的文献数 */
            updated: number;
            /** @description 跳过（无 markdown/已完整/LLM 未给出新字段）的文献数 */
            skipped: number;
            /** @description 处理失败（LLM 错误/JSON 解析失败/DB 错误）的文献数 */
            failed: number;
            /** @description 处理后仍待处理的篇数（剩余）：满足 onlyMissing 条件、尚未回填的文献数，不受 limit 截断 */
            available: number;
        };
        PaperExtractionDto: {
            /** @description 核心研究问题或研究目标 */
            researchQuestion?: string | null;
            /** @description 研究方法或技术路线 */
            method?: string | null;
            /** @description 主要研究发现或结论 */
            findings?: string | null;
            /** @description 使用的数据集或数据来源 */
            dataset?: string | null;
            /** @description 主要学术贡献或创新点 */
            contribution?: string | null;
        };
        ExtractStructuredRequest: {
            /** @description 最多处理的文献数（保配额） */
            limit?: number;
            /** @description True=强制重新抽取（覆盖已有 extraction）；False=跳过已有 */
            reextract?: boolean;
        };
        ExtractStructuredResult: {
            /** @description 本次处理的文献总数 */
            processed: number;
            /** @description 成功抽取（新建或更新）的文献数 */
            extracted: number;
            /** @description 跳过（无 markdown/已有 extraction 且未强制重提取）的文献数 */
            skipped: number;
            /** @description 处理失败（LLM 错误/JSON 解析失败/DB 错误）的文献数 */
            failed: number;
            /** @description 处理后仍待处理的篇数（剩余）：OCR done 且尚无 extraction 的文献数，reextract=true 时为 OCR done 总数，不受 limit 截断 */
            available: number;
        };
        /** @description 单篇文献详情，以 services/agent/app/schemas.py 的 PaperDetail Pydantic 模型为准。 extraction 字段为可选，无 paper_extraction 记录时为 null。 */
        PaperDetail: {
            /** @description 文献 DB 主键 */
            paperId: number;
            /** @description 文献标题 */
            title?: string | null;
            /** @description 作者列表（CSL-JSON 格式，元素可为字符串或含 family/given/literal 的对象） */
            creators?: unknown[];
            /** @description DOI 标识符 */
            doi?: string | null;
            source?: string | null;
            /** @description 摘要正文 */
            abstract?: string | null;
            /** @description 用户标签列表 */
            tags?: string[];
            /** @description 用户笔记列表 */
            notes?: unknown[];
            /**
             * @description 纳排状态
             * @enum {string}
             */
            inclusionStatus: "candidate" | "included" | "excluded" | "maybe";
            /** @description LLM 结构化抽取结果；无抽取记录时为 null */
            extraction?: components["schemas"]["PaperExtractionDto"] | null;
        };
    };
    responses: never;
    parameters: {
        ProjectId: string;
        CorpusId: string;
        /** @description 上传重试去重键 (step1-P1) */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 健康 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    createCorpus: {
        parameters: {
            query?: never;
            header?: {
                /** @description 上传重试去重键 (step1-P1) */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    dbsource: components["schemas"]["DbSource"];
                };
            };
        };
        responses: {
            /** @description 已受理, 后台解析中 (status=parsing) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusRef"];
                };
            };
            /** @description 表单/参数校验失败 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrValidation"];
                };
            };
            /** @description 文件超限 (沿用 50MB) */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrPayloadTooLarge"];
                };
            };
            /** @description 不支持的文件类型/内容无法解析为所选 dbsource (step1-P2) */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrUnsupportedFile"];
                };
            };
        };
    };
    createCorpusFromTopic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopicRequest"];
            };
        };
        responses: {
            /** @description 已建库 (status=ready/failed) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusRef"];
                };
            };
            /** @description 参数校验失败 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrValidation"];
                };
            };
            /** @description OpenAlex 无结果或解析失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrValidation"];
                };
            };
        };
    };
    createCorpusFromRefs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefsRequest"];
            };
        };
        responses: {
            /** @description 已建库 (status=ready/failed) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusRef"];
                };
            };
            /** @description 未识别出论文条目或均未在 OpenAlex 匹配 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrValidation"];
                };
            };
        };
    };
    materializeCorpus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 项目 DB id（整数） */
                pid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 语料物化成功（ready 或已复用） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusMaterializeResponse"];
                };
            };
            /** @description 项目不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
            /** @description included 论文为空（EMPTY_INCLUDED） */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrValidation"];
                };
            };
            /** @description R 服务不可达或建库失败 */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrValidation"];
                };
            };
        };
    };
    getCorpus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                corpusId: components["parameters"]["CorpusId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 语料引用 (按状态强建模) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusRef"];
                };
            };
            /** @description 语料不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
        };
    };
    getOverview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                corpusId: components["parameters"]["CorpusId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 概览结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResult"];
                };
            };
            /** @description 语料不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
            /** @description 语料仍在解析 (CORPUS_NOT_READY, 可重试轮询) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotReady"];
                };
            };
            /** @description 语料解析失败的终态 (PARSE_FAILED, 不应重试; step1-P1) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrParseFailed"];
                };
            };
            /** @description R 服务返回坏响应 (ANALYSIS_FAILED) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrAnalysisFailed"];
                };
            };
            /** @description R 服务不可达/熔断 (R_SERVICE_UNAVAILABLE; step1-P1, 区别于 502) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrRUnavailable"];
                };
            };
        };
    };
    getSources: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                corpusId: components["parameters"]["CorpusId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 来源分析结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcesResult"];
                };
            };
            /** @description 语料不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
            /** @description 语料未就绪 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotReady"];
                };
            };
        };
    };
    getAuthors: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                corpusId: components["parameters"]["CorpusId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 作者分析结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorsResult"];
                };
            };
            /** @description 语料不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
            /** @description 语料未就绪 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotReady"];
                };
            };
        };
    };
    getDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                corpusId: components["parameters"]["CorpusId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 文档与关键词结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentsResult"];
                };
            };
            /** @description 语料不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
            /** @description 语料未就绪 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotReady"];
                };
            };
        };
    };
    getAuthorProduction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                corpusId: components["parameters"]["CorpusId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 作者年度产出信封 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorProductionEnvelope"];
                };
            };
            /** @description 语料不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
            /** @description 语料未就绪 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotReady"];
                };
            };
        };
    };
    getKeywordTrend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                corpusId: components["parameters"]["CorpusId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 关键词历时演变信封 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeywordTrendEnvelope"];
                };
            };
            /** @description 语料不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
            /** @description 语料未就绪 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotReady"];
                };
            };
        };
    };
    getCitedRefs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                corpusId: components["parameters"]["CorpusId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 高被引参考文献信封 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CitedRefsEnvelope"];
                };
            };
            /** @description 语料不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
            /** @description 语料未就绪 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotReady"];
                };
            };
        };
    };
    getThematic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                corpusId: components["parameters"]["CorpusId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 主题战略图信封 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThematicEnvelope"];
                };
            };
            /** @description 语料不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
            /** @description 语料未就绪 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotReady"];
                };
            };
        };
    };
    getEvolution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                corpusId: components["parameters"]["CorpusId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 主题演进图信封 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvolutionEnvelope"];
                };
            };
            /** @description 语料不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
            /** @description 语料未就绪 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotReady"];
                };
            };
        };
    };
    getHistcite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                corpusId: components["parameters"]["CorpusId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 历史引文图信封 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistciteEnvelope"];
                };
            };
            /** @description 语料不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
            /** @description 语料未就绪 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotReady"];
                };
            };
        };
    };
    getThreeField: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                corpusId: components["parameters"]["CorpusId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 三字段 Sankey 信封 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreeFieldEnvelope"];
                };
            };
            /** @description 语料不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
            /** @description 语料未就绪 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotReady"];
                };
            };
        };
    };
    getConceptual: {
        parameters: {
            query?: {
                /** @description 返回 top-N 节点 (按强度); 前端滑块客户端切片 */
                limit?: number;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                corpusId: components["parameters"]["CorpusId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 关键词共现网络 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkResult"];
                };
            };
            /** @description 语料不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
            /** @description 语料未就绪 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotReady"];
                };
            };
        };
    };
    getIntellectual: {
        parameters: {
            query?: {
                /** @description 返回 top-N 节点 (按强度); 前端滑块客户端切片 */
                limit?: number;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                corpusId: components["parameters"]["CorpusId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 共被引网络 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkResult"];
                };
            };
            /** @description 语料不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
            /** @description 语料未就绪 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotReady"];
                };
            };
        };
    };
    getSocial: {
        parameters: {
            query?: {
                /** @description 返回 top-N 节点 (按强度); 前端滑块客户端切片 */
                limit?: number;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                corpusId: components["parameters"]["CorpusId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 合作网络 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SocialResult"];
                };
            };
            /** @description 语料不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
            /** @description 语料未就绪 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotReady"];
                };
            };
        };
    };
    getLibraryStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 全局文献库统计 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryStats"];
                };
            };
        };
    };
    getProjectLibraryStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 项目文献库统计 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectLibraryStats"];
                };
            };
            /** @description 项目不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
        };
    };
    getPaperDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                paperId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 单篇文献详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperDetail"];
                };
            };
            /** @description 项目或文献不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
        };
    };
    importPapers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** @description 一个或多个 .pdf 文件，或一个 .zip 文件（内含 PDF） */
                    files: string[];
                    /**
                     * @description 导入后的默认纳排状态
                     * @default candidate
                     * @enum {string}
                     */
                    default_status?: "candidate" | "included" | "excluded" | "maybe";
                };
            };
        };
        responses: {
            /** @description 导入结果（含 imported/skipped/failed/paperIds） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PapersImportResponse"];
                };
            };
            /** @description 参数校验失败（缺少文件、非法 default_status 等） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrValidation"];
                };
            };
            /** @description 项目不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
        };
    };
    addPapersFromSearch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FromSearchRequest"];
            };
        };
        responses: {
            /** @description 入库结果（含 imported/skipped/paperIds） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FromSearchResult"];
                };
            };
            /** @description 项目不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
        };
    };
    backfillMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BackfillMetadataRequest"];
            };
        };
        responses: {
            /** @description 元数据补全结果（含 processed/updated/skipped/failed） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackfillMetadataResult"];
                };
            };
            /** @description 项目不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
        };
    };
    extractStructured: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractStructuredRequest"];
            };
        };
        responses: {
            /** @description 结构化抽取结果（含 processed/extracted/skipped/failed） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractStructuredResult"];
                };
            };
            /** @description 项目不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
        };
    };
    buildPrisma: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrismaRequest"];
            };
        };
        responses: {
            /** @description PRISMA 流程结构 (含 warnings) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrismaResult"];
                };
            };
            /** @description 计数非法 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrValidation"];
                };
            };
        };
    };
    exportReport: {
        parameters: {
            query?: {
                format?: "md" | "html" | "docx";
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                corpusId: components["parameters"]["CorpusId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReportOptions"];
            };
        };
        responses: {
            /** @description 报告文件 (附件) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/markdown": string;
                    "text/html": string;
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": string;
                };
            };
            /** @description format 非法 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrValidation"];
                };
            };
            /** @description 语料不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
            /** @description DOCX 不可用 (pandoc 缺失/超时) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrValidation"];
                };
            };
        };
    };
    aiTranslate: {
        parameters: {
            query?: never;
            header?: {
                "X-LLM-Key"?: string;
            };
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranslateRequest"];
            };
        };
        responses: {
            /** @description 译文 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextResult"];
                };
            };
            /** @description 参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrValidation"];
                };
            };
        };
    };
    aiRewrite: {
        parameters: {
            query?: never;
            header?: {
                "X-LLM-Key"?: string;
            };
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RewriteRequest"];
            };
        };
        responses: {
            /** @description 重写结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextResult"];
                };
            };
            /** @description 参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrValidation"];
                };
            };
        };
    };
    aiSummary: {
        parameters: {
            query?: never;
            header?: {
                "X-LLM-Key"?: string;
            };
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SummaryRequest"];
            };
        };
        responses: {
            /** @description 总结 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextResult"];
                };
            };
        };
    };
    aiScreen: {
        parameters: {
            query?: never;
            header?: {
                "X-LLM-Key"?: string;
            };
            path: {
                projectId: components["parameters"]["ProjectId"];
                corpusId: components["parameters"]["CorpusId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScreenRequest"];
            };
        };
        responses: {
            /** @description 筛选结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenResult"];
                };
            };
            /** @description 语料不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
        };
    };
    aiChat: {
        parameters: {
            query?: never;
            header?: {
                "X-LLM-Key"?: string;
            };
            path: {
                projectId: components["parameters"]["ProjectId"];
                corpusId: components["parameters"]["CorpusId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description SSE 流 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description 语料不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
        };
    };
    getCite: {
        parameters: {
            query?: {
                style?: "gbt7714" | "apa" | "mla";
                limit?: number;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                corpusId: components["parameters"]["CorpusId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 引用列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CiteResult"];
                };
            };
            /** @description style 非法 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrValidation"];
                };
            };
            /** @description 语料不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
        };
    };
    streamReview: {
        parameters: {
            query?: never;
            header?: {
                /** @description 用户自带 LLM API key (会话级, 不落盘); 缺省用服务端 key 或 fake */
                "X-LLM-Key"?: string;
            };
            path: {
                projectId: components["parameters"]["ProjectId"];
                corpusId: components["parameters"]["CorpusId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description SSE 流 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description 未知论型 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrValidation"];
                };
            };
            /** @description 语料不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
        };
    };
    listArtifacts: {
        parameters: {
            query?: {
                pinned?: boolean;
            };
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 工件列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        artifacts?: components["schemas"]["ArtifactItem"][];
                    };
                };
            };
            /** @description 项目不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArtifactCreateRequest"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactItem"];
                };
            };
        };
    };
    deleteArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: number;
                aid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 工件不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patchArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: number;
                aid: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArtifactPatchRequest"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactItem"];
                };
            };
            /** @description 工件不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
